
# This version number is read by both pyp and micromon.
# It is shown directly to the user in micromon's user interface.
# To the extent that is feasible, it should follow Semantic Versioning conventions:
# https://semver.org/
version = "0.5.3"
